
$background = rgba(13140dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303129ff)

$inverse_primary = rgba(5a631fff)

$inverse_surface = rgba(e4e3d6ff)

$on_background = rgba(e4e3d6ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(2d3400ff)

$on_primary_container = rgba(deea96ff)

$on_primary_fixed = rgba(191e00ff)

$on_primary_fixed_variant = rgba(424b06ff)

$on_secondary = rgba(2f321aff)

$on_secondary_container = rgba(e2e5c2ff)

$on_secondary_fixed = rgba(1a1d07ff)

$on_secondary_fixed_variant = rgba(45492fff)

$on_surface = rgba(e4e3d6ff)

$on_surface_variant = rgba(c8c7b7ff)

$on_tertiary = rgba(06372eff)

$on_tertiary_container = rgba(bdecdeff)

$on_tertiary_fixed = rgba(00201aff)

$on_tertiary_fixed_variant = rgba(224e44ff)

$outline = rgba(919283ff)

$outline_variant = rgba(47483bff)

$primary = rgba(c2cd7cff)

$primary_container = rgba(424b06ff)

$primary_fixed = rgba(deea96ff)

$primary_fixed_dim = rgba(c2cd7cff)

$scrim = rgba(000000ff)

$secondary = rgba(c6c9a7ff)

$secondary_container = rgba(45492fff)

$secondary_fixed = rgba(e2e5c2ff)

$secondary_fixed_dim = rgba(c6c9a7ff)

$shadow = rgba(000000ff)

$source_color = rgba(4f5335ff)

$surface = rgba(13140dff)

$surface_bright = rgba(393a31ff)

$surface_container = rgba(1f2018ff)

$surface_container_high = rgba(2a2b22ff)

$surface_container_highest = rgba(35352dff)

$surface_container_low = rgba(1b1c15ff)

$surface_container_lowest = rgba(0e0f08ff)

$surface_dim = rgba(13140dff)

$surface_tint = rgba(c2cd7cff)

$surface_variant = rgba(47483bff)

$tertiary = rgba(a2d0c2ff)

$tertiary_container = rgba(224e44ff)

$tertiary_fixed = rgba(bdecdeff)

$tertiary_fixed_dim = rgba(a2d0c2ff)


